<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getArticleSample($category = NULL, $number){
        $qb = $this->createQueryBuilder('a');
        $qb->select('a.id', 'a.title', 'a.img', 'a.content');
        $qb->where('a.visible = 1');
       //     if($category != NULL) {
                $qb->andWhere('c.name = :category');
                    $qb->setParameter('category', $category);
                    $qb->innerJoin('a.categories', 'c');
      //      };
        $qb->setMaxResults($number);
        $qb->orderBy('a.id', 'DESC');
        return $qb->getQuery()->getResult();
    }

}
