<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getContent($category, $number){
        $qb= $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.visible = 1')
            ->andWhere('a.category = :category')
            ->setMaxResults(':number')
            ->orderBy('c.id', 'ASC')
            ->setParameters(['category' => $category, 'number' => $number])
            ->getQuery();
        return $qb->getResult();
    }

}
