<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository
{
    public function getContent($type){
        $qb= $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.visible = 1')
            ->andWhere('c.category = :type')
            ->orderBy('c.id', 'DESC')
            ->setParameter('type', $type)
            ->getQuery();
        return $qb->getResult();
    }

}
