<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * logbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class logbookRepository extends EntityRepository
{
}
