<?php

namespace BlogBundle\Repository;

/**
 * LogcomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogcomRepository extends \Doctrine\ORM\EntityRepository
{
}
