<?php

namespace BlogBundle\Repository;

/**
 * SkillDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
