blog_main:
    resource: "@BlogBundle/Resources/config/routing/main.yml"
    prefix:   /

blog_logbook:
    resource: "@BlogBundle/Resources/config/routing/logbook.yml"
    prefix:   /logbook

blog_category:
    resource: "@BlogBundle/Resources/config/routing/category.yml"
    prefix:   /category
