site_main:
    resource: "@BlogBundle/Resources/config/routing/main.yml"
    prefix:   /

blog_main:
    resource: "@BlogBundle/Resources/config/routing/blog.yml"
    prefix:   /blog

blog_article:
    resource: "@BlogBundle/Resources/config/routing/article.yml"
    prefix:   /article


