blog_index:
    path:     /
    defaults: { _controller: "BlogBundle:Blog:index" }
    methods:  GET

blog_article:
    path:     /blog_article
    defaults: { _controller: BlogBundle:Blog:article }
    methods:  GET

blog_tagindex:
    path:     /tagindex/{tag}
    defaults: { _controller: BlogBundle:Blog:tagindex }
    methods: [POST, GET]
