logbook_index:
    path:     /
    defaults: { _controller: "BlogBundle:Logbook:index" }
    methods:  GET

logbook_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:Logbook:show" }
    methods:  GET

logbook_new:
    path:     /new
    defaults: { _controller: "BlogBundle:Logbook:new" }
    methods:  [GET, POST]

logbook_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:Logbook:edit" }
    methods:  [GET, POST]

logbook_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:Logbook:delete" }
    methods:  DELETE
