index:
    path:     /
    defaults: { _controller: BlogBundle:Main:index }

resume:
    path:     /resume
    defaults: { _controller: BlogBundle:Main:resume }

profile:
    path:     /contact
    defaults: { _controller: BlogBundle:Main:profile }

logbook:
    path:     /logbook
    defaults: { _controller: BlogBundle:Main:logbook }

settings:
    path:     /settings
    defaults: { _controller: BlogBundle:Main:settings }

project:
    path:     /project
    defaults: { _controller: BlogBundle:Main:project }

blog:
    path:     /blog