index:
    path:     /
    defaults: { _controller: BlogBundle:Main:index }

logbook:
    path:     /logbook
    defaults: { _controller: BlogBundle:Main:logbook }

settings:
    path:     /settings
    defaults: { _controller: BlogBundle:Main:settings }

resume:
    path:     /CV
    defaults: { _controller: BlogBundle:Main:resume }

resume2:
    path:     /CV2
    defaults: { _controller: BlogBundle:Main:resume2 }

project:
    path:     /project
    defaults: { _controller: BlogBundle:Main:project }

blog:
    path:     /blog