index:
    path:     /
    defaults: { _controller: "BlogBundle:Main:index" }
    methods:  GET

resume:
    path:     /CV
    defaults: { _controller: "BlogBundle:Main:resume" }
    methods:  GET

#project:
 #   path:     /project
  #  defaults: { _controller: BlogBundle:Main:project }