BlogBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true

    manyToMany:
        articles:
          targetEntity: Article
          mappedBy: categories
        contents:
            targetEntity: BlogBundle\Entity\Content
            mappedBy: categories
    lifecycleCallbacks: {  }
