BlogBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        subject:
            type: string
            length: 255
        content:
            type: text
        visible:
            type: boolean

    manyToOne:
        article:
            targetEntity: Article
            inversedBy: comments
            joinColumn:
                name: article_id
                referencedColumnName: id
        user:
            targetEntity: User
            inversedBy: comments
            joinColumn:
                name: user_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
