BlogBundle\Entity\Content:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\ContentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        subtitle:
            type: string
            length: 255
            nullable: true
        category:
            type: string
            length: 255
            nullable: true
        content:
            type: text
            nullable: true
        other:
            type: string
            length: 255
            nullable: true
        img:
            type: string
            length: 255
            nullable: true
        url:
            type: string
            length: 255
            nullable: true
        visible:
            type: boolean
    lifecycleCallbacks: {  }
