BlogBundle\Entity\Logbook:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\LogbookRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
          nullable: true
          type: date
          gedmo:
            timestampable:
              on: create
        title:
            type: string
            length: 255
        content:
            type: text
        img:
            type: string
            length: 255
            nullable: true
        other:
            type: string
            length: 255
            nullable: true

    lifecycleCallbacks: {  }
